name: AgriPlus
#
main: mas.agri.Main
#
version: 1.2.6 Alpha
#
developers: [Stormcraftking, Masterlu]
#
commands:
  aplus:
#
permissions:
  aplus.reload.plugman:
    default: op
  aplus.reload.config:
    default: op
  aplus.help.main:
    default: op
  aplus.help.machine:
    default: op
