name: AgriPlus
main: mas.agri.Main
version: 1.0 Alpha
developers: [Stormcraftking, Masterlu]
commands:
  agriculture:
permissions:
  agriplus:
    default: op
  a+:
permissions:
  aplus:
    default: op
